import type { PersonalArtwork } from "./personal";

type Chapter = {
  readonly eyebrow: string;
  readonly headline: readonly string[];
  readonly accent?: string;
  readonly body: readonly string[];
  readonly items?: readonly string[];
  readonly artwork?: PersonalArtwork;
  readonly tone?: "white" | "quiet" | "deep";
  readonly layout?: "split" | "statement" | "sequence" | "principles";
  readonly reverse?: boolean;
  readonly boundary?: string;
};

export type InnerStoryPage = {
  readonly slug: string;
  readonly eyebrow: string;
  readonly title: readonly string[];
  readonly accent: string;
  readonly proposition?: string;
  readonly lead: string;
  readonly qualifier?: string;
  readonly heroArtwork: PersonalArtwork;
  readonly chapters: readonly Chapter[];
  readonly closing: { readonly headline: readonly string[]; readonly accent?: string; readonly body: string; readonly ctas: readonly { readonly label: string; readonly href: string }[] };
  readonly next: { readonly eyebrow: "Next chapter"; readonly headline: readonly string[]; readonly body: string; readonly cta: string; readonly href: string };
};

const art = (assetKey: string, title: string, description: string, aspectRatio: PersonalArtwork["aspectRatio"], mobileAspectRatio: PersonalArtwork["mobileAspectRatio"], brief: string): PersonalArtwork => ({ assetKey, title, description, aspectRatio, mobileAspectRatio, brief });
const next = (headline: readonly string[], body: string, cta: string, href: string) => ({ eyebrow: "Next chapter" as const, headline, body, cta, href });

export const innerSitePages = {
  "why-vascurra": {
    slug: "why-vascurra", eyebrow: "Why Vascurra", title: ["Cognitive health does not only happen", "between appointments."], accent: "between appointments.", proposition: "Life happens every day. Healthcare sees only moments of it.", lead: "People live their lives between consultations. Questions appear, routines shift, family members notice things and clinicians see moments—while meaningful context can remain fragmented.",
    heroArtwork: art("why-vascurra-hero", "Life between appointments", "Everyday context gradually becoming connected.", "4 / 5", "4 / 5", "One continuous Vascurra ribbon moving through ordinary life moments and gradually bringing scattered context together. No brain imagery."),
    chapters: [
      { eyebrow: "Life between appointments", headline: ["Most of life happens", "outside the consultation room."], accent: "outside the consultation room.", body: ["Routines, confidence, mobility, eating, sleep, memory, social connection, everyday function and meaningful events can all provide useful context when a person chooses to record them.", "They are parts of a life—not automatic biomarkers or proof of progression."], layout: "split" },
      { eyebrow: "The fragmented picture", headline: ["Everyone sees a piece.", "Few see the whole picture."], accent: "Few see the whole picture.", body: ["The person, family, clinicians and researchers may each hold a different perspective. No single view is complete, and none should silently overrule the person at the centre."], items: ["Person", "Family", "Clinician", "Research"], artwork: art("why-vascurra-perspectives", "Perspectives around one person", "Different views remain distinct while useful context connects.", "16 / 7", "4 / 3", "Four lightly connected perspectives around one person, with open paths and no surveillance metaphor."), tone: "quiet", layout: "principles" },
      { eyebrow: "The information problem", headline: ["More information", "is not always more understanding."], accent: "is not always more understanding.", body: ["Collection is not the goal. Meaning depends on relevance, source, timing and context—and on keeping interpretation separate from what was actually observed."], items: ["Relevance", "Provenance", "Time", "Context"], layout: "principles" },
      { eyebrow: "The clinical reality", headline: ["A consultation matters.", "Time is limited."], accent: "Time is limited.", body: ["Clinical conversations matter. Arriving with relevant questions and well-organised context may make that limited time easier to use without adding another wall of information."], layout: "statement" },
      { eyebrow: "It began with Dad", headline: ["A systemic problem.", "A human starting point."], accent: "A human starting point.", body: ["Vascurra began with a father, a retired GP, and the everyday questions that appeared when he experienced healthcare from the other side.", "That origin keeps the project grounded in usefulness, dignity and the things that matter tomorrow morning."], layout: "split" },
      { eyebrow: "The opportunity", headline: ["What if intelligence", "helped connect the context?"], accent: "helped connect the context?", body: ["Vascurra is exploring how carefully governed technology might help organise meaningful context, support preparation and make complexity easier to navigate."], boundary: "This is a project direction, not evidence of clinical effectiveness or live medical functionality.", tone: "deep", layout: "statement" },
    ], closing: { headline: ["Start with a human problem.", "Build carefully from there."], accent: "Build carefully from there.", body: "Vascurra begins with lived experience and lets evidence determine what can responsibly follow.", ctas: [{ label: "Discover Patient 0", href: "/patient-0" }] }, next: next(["One person can be", "a thoughtful beginning."], "See how co-design turns a human starting point into a disciplined way of building.", "Explore Patient 0", "/patient-0"),
  },
  "patient-0": {
    slug: "patient-0", eyebrow: "Patient 0", title: ["Start with one person.", "Learn deeply.", "Build for many."], accent: "Build for many.", lead: "Vascurra begins by understanding one person’s real experience deeply enough to design something genuinely useful.", qualifier: "Patient 0 means co-design. It does not mean a clinical trial, medical experiment or evidence of effectiveness.", heroArtwork: art("patient-zero-hero", "A human starting point", "Dignified co-design rooted in real life.", "4 / 5", "4 / 5", "Dignified human imagery derived from the approved Dad and Origin language, with one open Vascurra ribbon and generous white space."),
    chapters: [
      { eyebrow: "Co-design, not observation", headline: ["Build with the person.", "Not around them."], accent: "Build with the person.", body: ["The person is a participant in design, not an object being watched. Their goals, preferences, strengths and limits should shape what is built and what is left out."], layout: "split" },
      { eyebrow: "Real life", headline: ["Begin with", "what actually happens."], accent: "what actually happens.", body: ["Good design starts with ordinary questions rather than assumptions made at a distance."], items: ["What creates friction?", "What provides confidence?", "What gets forgotten?", "What feels unnecessary?", "What deserves support?"], tone: "quiet", layout: "principles" },
      { eyebrow: "The design test", headline: ["Would this genuinely be useful", "tomorrow morning?"], accent: "tomorrow morning?", body: ["A simple test keeps ambition connected to real life: can this make something clearer, calmer or more manageable when the next day begins?"], tone: "deep", layout: "statement" },
      { eyebrow: "Real questions", headline: ["Lived experience reveals", "questions worth asking."], accent: "questions worth asking.", body: ["Questions from daily life can expose friction, missing context and opportunities for better support. They are starting points for design and research—not findings in themselves."], layout: "split" },
      { eyebrow: "Continuous co-design", headline: ["Build. Use. Observe.", "Discuss. Improve."], accent: "Discuss. Improve.", body: ["The learning cycle should remain visible, revisitable and accountable to the person using it."], items: ["Build", "Use", "Observe", "Discuss", "Improve"], artwork: art("patient-zero-loop", "The co-design loop", "A continuous path of use and discussion.", "16 / 7", "4 / 3", "One elegant continuous ribbon moving through five co-design moments; not a corporate circular-process diagram."), layout: "sequence" },
      { eyebrow: "From one to many", headline: ["One person is a starting point.", "Not a universal answer."], accent: "Not a universal answer.", body: ["One person’s experience does not represent everyone. The purpose is to learn how to listen, test and build responsibly—not turn an individual story into universal evidence."], layout: "statement" },
    ], closing: { headline: ["Learn deeply.", "Build responsibly."], accent: "Build responsibly.", body: "The first lesson is not scale. It is attention.", ctas: [{ label: "See how Vascurra works", href: "/how-it-works" }] }, next: next(["A human beginning needs", "a clear framework."], "Follow the conceptual loop from chosen context to useful support and learning.", "How Vascurra works", "/how-it-works"),
  },
  "how-it-works": {
    slug: "how-it-works", eyebrow: "How Vascurra works", title: ["Observe.", "Understand.", "Support. Learn."], accent: "Support. Learn.", lead: "A continuous learning framework built around meaningful context over time.", qualifier: "A conceptual framework—not a clinical score, diagnostic device or autonomous medical system.", heroArtwork: art("how-it-works-framework", "The continuous framework", "Four connected stages around real life.", "16 / 7", "4 / 3", "A refined continuous Vascurra loop with Observe, Understand, Support and Learn expressed through rhythm rather than a corporate diagram."),
    chapters: [
      { eyebrow: "Observe", headline: ["Notice", "what matters."], accent: "what matters.", body: ["Chosen observations, measurements, routines and events can contribute context. The intention is meaningful attention—not constant monitoring."], layout: "split" },
      { eyebrow: "Understand", headline: ["Connect", "the context."], accent: "the context.", body: ["Bring relevant information together while preserving its source, timing and uncertainty. An observation should remain distinguishable from an interpretation."], tone: "quiet", layout: "split", reverse: true },
      { eyebrow: "Support", headline: ["Make understanding", "useful."], accent: "useful.", body: ["Useful support may help a person prepare, navigate, remember, ask and review—without deciding for them."], items: ["Prepare", "Navigate", "Remember", "Ask", "Review"], layout: "principles" },
      { eyebrow: "Learn", headline: ["Learn from", "what happens next."], accent: "what happens next.", body: ["Feedback and evidence can improve future design. Learning remains governed and reviewed; it is not autonomous medicine adapting beyond human oversight."], layout: "statement" },
      { eyebrow: "Multiple perspectives", headline: ["One system.", "Different permitted views."], accent: "Different permitted views.", body: ["Personal, Family, Clinician and Research perspectives may eventually use appropriate parts of the same underlying context for different purposes."], items: ["Personal", "Family", "Clinician", "Research"], artwork: art("how-it-works-perspectives", "One system, multiple perspectives", "Permission-appropriate views around one person.", "16 / 7", "4 / 3", "An elegant system view with the person central and four clearly distinct, selectively connected perspectives."), layout: "sequence" },
      { eyebrow: "A living picture", headline: ["Not a score. Not a snapshot.", "A picture over time."], accent: "A picture over time.", body: ["Connected context can make change easier to discuss without compressing a person into an unexplained number."], boundary: "Conceptual framework— not a clinical score or diagnostic device.", tone: "deep", layout: "statement" },
    ], closing: { headline: ["Context becomes more useful", "when it stays connected."], accent: "when it stays connected.", body: "The person remains central as the picture develops.", ctas: [{ label: "Explore the Personal perspective", href: "/personal" }] }, next: next(["A framework becomes meaningful", "in everyday life."], "See how Personal support can adapt around a person without taking over.", "For people", "/personal"),
  },
  families: {
    slug: "families", eyebrow: "For Families", title: ["Closer together.", "Without taking over."], accent: "Without taking over.", lead: "Family support should create connection, preparation and confidence—without turning care into surveillance.", qualifier: "Family access would never be automatic. Sharing must be permission-appropriate and subject to consent, capacity and applicable safeguards.", heroArtwork: art("family-hero", "Connected without control", "A person remains central within supportive relationships.", "4 / 5", "4 / 5", "A person at the centre with family nearby, connected by a gentle open ribbon that never encloses or controls them."),
    chapters: [
      { eyebrow: "Know what matters", headline: ["Useful context.", "Not constant monitoring."], accent: "Not constant monitoring.", body: ["Support can focus on what the person chooses to share: relevant questions, practical changes and context that may help a conversation."], layout: "split" },
      { eyebrow: "Support without surveillance", headline: ["Care should feel", "like care."], accent: "like care.", body: ["Connection should not require watching everything. Vascurra’s direction is selective, understandable support that can become quieter when it is not useful."], tone: "deep", layout: "statement" },
      { eyebrow: "Prepare together", headline: ["Bring the right things", "into the conversation."], accent: "into the conversation.", body: ["Shared preparation may make practical moments easier without transferring control away from the person."], items: ["Appointments", "Questions", "Practical tasks", "Important observations"], artwork: art("family-prepare", "Prepare together", "Chosen context moving toward a shared conversation.", "16 / 7", "4 / 3", "An elegant preparation pathway connecting selected questions and practical context; no checklist dashboard."), layout: "sequence" },
      { eyebrow: "Sharing is not automatic", headline: ["Closer.", "With permission."], accent: "With permission.", body: ["The person remains central. Permissions should be specific, understandable and revisitable, and access may differ for every relationship and purpose."], artwork: art("family-permissions", "Selective family permissions", "Connections open only where chosen.", "16 / 8", "4 / 3", "One central person with selectively open family connections; no surveillance, lock or enclosing ring."), layout: "split", reverse: true },
      { eyebrow: "Different people, different roles", headline: ["A relationship does not", "grant automatic access."], accent: "grant automatic access.", body: ["A partner, adult child or other trusted person may support in different ways. No role should automatically see everything, and capacity considerations require careful safeguards."], items: ["Partner", "Adult child", "Other trusted person"], tone: "quiet", layout: "principles" },
      { eyebrow: "Less guesswork", headline: ["Better context.", "Calmer conversations."], accent: "Calmer conversations.", body: ["The aim is not certainty. It is a clearer starting point for talking about what matters."], layout: "statement" },
    ], closing: { headline: ["Support the person.", "Not just the condition."], accent: "Support the person.", body: "Care can stay connected while agency stays where it belongs.", ctas: [{ label: "For clinicians", href: "/clinicians" }] }, next: next(["Shared context can support", "a better-prepared consultation."], "Explore how the clinical perspective keeps provenance and human judgement visible.", "For clinicians", "/clinicians"),
  },
  clinicians: {
    slug: "clinicians", eyebrow: "For Clinicians", title: ["Better context.", "Better conversations."], accent: "Better conversations.", lead: "Relevant longitudinal context without another wall of data.", qualifier: "All clinical experiences shown are conceptual product direction. Vascurra does not currently provide clinical functionality.", heroArtwork: art("clinician-hero", "Context prepared for review", "Lived context becomes a concise consultation-ready view.", "16 / 7", "4 / 3", "A refined flow from lived context into a concise consultation-ready view. No fake dashboard, score or stock doctor."),
    chapters: [
      { eyebrow: "Between appointments", headline: ["The consultation is one moment.", "The context extends beyond it."], accent: "The context extends beyond it.", body: ["Relevant history may develop over days and weeks. Organising selected context could support preparation while respecting the value and limits of consultation time."], layout: "split" },
      { eyebrow: "Less noise, more provenance", headline: ["Keep the trail", "visible."], accent: "visible.", body: ["A useful summary should not erase how information came to be. Report, source, time, context and interpretation need to remain distinguishable before human review."], items: ["Observation", "Source", "Time", "Context", "Interpretation", "Human review"], artwork: art("clinician-provenance", "The provenance trail", "Source-aware context prepared for review.", "16 / 7", "4 / 3", "A fine linear flow from observation through source, time and context to interpretation and human review; no dashboard."), tone: "quiet", layout: "sequence" },
      { eyebrow: "Prepare the conversation", headline: ["What deserves", "discussion?"], accent: "discussion?", body: ["The useful question is not what an AI should decide. It is what the person and clinician may want to discuss, verify or place in context."], layout: "statement" },
      { eyebrow: "Longitudinal context", headline: ["Review change", "without predicting it."], accent: "without predicting it.", body: ["A sequence of source-linked observations may be easier to review than isolated notes. Patterns can support questions; they must not be presented as autonomous predictions or diagnoses."], layout: "split" },
      { eyebrow: "Human judgement", headline: ["Organise context.", "Do not practise medicine."], accent: "Do not practise medicine.", body: ["Vascurra is intended to support human clinical judgement, not replace it. Clinical decisions remain with appropriately qualified professionals."], tone: "deep", layout: "statement" },
      { eyebrow: "Conceptual product direction", headline: ["A quieter path", "to what matters."], accent: "to what matters.", body: ["Potential future experiences include visit preparation, source-linked context, questions for review, longitudinal summaries and visible patient priorities."], items: ["Visit preparation", "Source-linked context", "Questions for review", "Patient priorities"], boundary: "These concepts are not live clinical functionality.", layout: "principles" },
    ], closing: { headline: ["More context.", "Less searching."], accent: "Less searching.", body: "Keep the source visible and the judgement human.", ctas: [{ label: "Explore Vascurra Intelligence", href: "/intelligence" }] }, next: next(["Behind useful context sits", "governed interpretation."], "See how Vascurra Intelligence is intended to preserve source, context and uncertainty.", "Vascurra Intelligence", "/intelligence"),
  },
  veya: {
    slug: "veya", eyebrow: "Veya", title: ["Your way", "through Vascurra."], accent: "through Vascurra.", lead: "A calm conversational layer designed to make complexity more understandable.", qualifier: "Veya is proposed. It is not a doctor, diagnostic system, emergency service, medication adviser or replacement for clinical judgement.", heroArtwork: art("veya-signature", "Veya signature", "A calm presence emerging from the Vascurra ribbon.", "4 / 5", "4 / 5", "A refined sculptural Veya form emerging from the Vascurra ribbon. No brain, robot, face, avatar, chat bubble or generic AI orb."),
    chapters: [
      { eyebrow: "Conversation as interface", headline: ["Sometimes the simplest interface", "is a conversation."], accent: "is a conversation.", body: ["Veya is the planned human-facing way through Vascurra: a place to ask, understand, organise and prepare in language that feels calm and direct."], layout: "split" },
      { eyebrow: "What Veya may help with", headline: ["Begin with a question.", "Keep the person in control."], accent: "Keep the person in control.", body: ["The person chooses what to explore and what context to capture."], items: ["Understand", "Capture chosen context", "Prepare", "Remember", "Navigate", "Surface questions"], tone: "quiet", layout: "sequence" },
      { eyebrow: "Plain language", headline: ["Complex information.", "Clearer language."], accent: "Clearer language.", body: ["Explanation should reduce unnecessary complexity without hiding nuance, uncertainty or source."], layout: "statement" },
      { eyebrow: "Context, not just answers", headline: ["Context.", "Not just answers."], accent: "Not just answers.", body: ["Relevant context can make a conversation more useful, but provenance and uncertainty should travel with every interpretation."], layout: "split" },
      { eyebrow: "Three distinct layers", headline: ["Conversation. Interpretation.", "Research-learning."], accent: "Research-learning.", body: ["Veya is the conversation layer. Vascurra Intelligence is the proposed governed interpretation layer. Vascurra Lab is the future research-learning layer."], items: ["Veya — Conversation layer", "Vascurra Intelligence — Reasoning and interpretation layer", "Vascurra Lab — Research-learning layer"], artwork: art("veya-intelligence-relationship", "Three distinct layers", "Conversation, governed interpretation and research-learning remain distinct.", "16 / 7", "4 / 3", "Three clearly distinct Vascurra layers connected vertically: calm conversation, source-aware governed interpretation and an open research-learning field."), layout: "sequence" },
      { eyebrow: "What Veya is not", headline: ["Calm support.", "Clear boundaries."], accent: "Clear boundaries.", body: ["Not a doctor. Not a diagnosis. Not an emergency service. Not medication advice. Not a replacement for clinical judgement."], tone: "deep", layout: "statement" },
    ], closing: { headline: ["Complexity,", "made more understandable."], accent: "made more understandable.", body: "A quieter route through information—without pretending to replace people who know and care.", ctas: [{ label: "Explore Vascurra Intelligence", href: "/intelligence" }] }, next: next(["Conversation needs", "a trustworthy foundation."], "Explore the governed interpretation layer proposed beneath Veya.", "Vascurra Intelligence", "/intelligence"),
  },
  intelligence: {
    slug: "intelligence", eyebrow: "Vascurra Intelligence", title: ["From information", "to understanding."], accent: "to understanding.", lead: "A proposed governed reasoning and interpretation layer beneath Veya.", qualifier: "A future concept—not an autonomous clinical decision-maker or authoritative health record.", heroArtwork: art("intelligence-hero", "Governed interpretation", "Context remains connected to source and uncertainty.", "16 / 7", "4 / 3", "An evolved Vascurra context form with visible sources and open paths. Do not reuse the Hero brain or create a generic neural network."),
    chapters: [
      { eyebrow: "The inputs", headline: ["Different information.", "Different meaning."], accent: "Different meaning.", body: ["Observations, measurements, behaviours, events, clinical context and evidence may each contribute—but they are not interchangeable."], items: ["Observations", "Measurements", "Behaviours", "Events", "Clinical context", "Evidence"], layout: "sequence" },
      { eyebrow: "Context", headline: ["Information becomes more useful", "when context travels with it."], accent: "when context travels with it.", body: ["Time, circumstances, source and purpose help explain what a piece of information can—and cannot—mean."], layout: "split" },
      { eyebrow: "Provenance", headline: ["Where did this", "come from?"], accent: "come from?", body: ["Who recorded it? When? In what circumstances? The original trail should remain available rather than disappear inside a summary."], items: ["Source", "Time", "Original context", "Transformation"], tone: "quiet", layout: "principles" },
      { eyebrow: "Interpretation", headline: ["Observation", "is not interpretation."], accent: "is not interpretation.", body: ["Reported information, measured data, verified records, deterministic calculations, AI interpretation and clinician confirmation must remain distinguishable."], layout: "statement" },
      { eyebrow: "Uncertainty", headline: ["Knowing what we do not know", "matters too."], accent: "matters too.", body: ["A responsible system should make gaps and uncertainty visible instead of producing false precision."], layout: "split" },
      { eyebrow: "Human review", headline: ["Intelligence should support", "human judgement."], accent: "human judgement.", body: ["Important interpretations should lead to appropriate questions and review—not silent conclusions or autonomous clinical action."], tone: "deep", layout: "statement" },
      { eyebrow: "Three distinct layers", headline: ["Conversation. Interpretation.", "Research-learning."], accent: "Research-learning.", body: ["Veya is the conversation layer. Vascurra Intelligence is the governed interpretation layer. Vascurra Lab is the future research-learning layer."], items: ["Veya", "Vascurra Intelligence", "Vascurra Lab"], layout: "principles" },
    ], closing: { headline: ["Make context easier", "to review."], accent: "to review.", body: "Keep provenance visible, uncertainty honest and consequential judgement human.", ctas: [{ label: "For research", href: "/research" }] }, next: next(["Better interpretation can lead to", "better research questions."], "Explore a future research perspective grounded in consent, provenance and lived context.", "For research", "/research"),
  },
  research: {
    slug: "research", eyebrow: "For Research", title: ["Better questions begin", "with better context."], accent: "with better context.", lead: "A future research perspective grounded in lived questions, explicit consent and traceable evidence.", qualifier: "There is no existing Vascurra research dataset, trial or external researcher access.", heroArtwork: art("research-hero", "Signals becoming questions", "Small source-aware signals form a pattern worth investigating.", "16 / 7", "4 / 3", "Many small source-aware signals gradually forming a meaningful question, not a finding, score or certainty cue."),
    chapters: [
      { eyebrow: "Questions from real life", headline: ["Research questions can begin", "with lived questions."], accent: "with lived questions.", body: ["Everyday friction and uncertainty may reveal questions worth investigating. A lived question can inspire research without becoming evidence by itself."], layout: "split" },
      { eyebrow: "Longitudinal context", headline: ["Time can change", "what context means."], accent: "what context means.", body: ["Carefully governed information over time may support different questions from isolated snapshots. Vascurra does not yet hold such a research dataset."], tone: "quiet", layout: "statement" },
      { eyebrow: "Evidence + provenance", headline: ["Keep evidence connected", "to its trail."], accent: "to its trail.", body: ["Sources, methods, transformations and limitations should remain open to scrutiny."], items: ["Source", "Method", "Transformation", "Limitation"], layout: "principles" },
      { eyebrow: "Consent", headline: ["Useful research begins", "with trust."], accent: "with trust.", body: ["Participation and secondary use must be explicit, understood and governable. Personal information must never silently become research material."], tone: "deep", layout: "statement" },
      { eyebrow: "Responsible AI-assisted research", headline: ["Use AI as infrastructure.", "Keep science accountable."], accent: "Keep science accountable.", body: ["Potential roles include literature synthesis, question exploration and bounded analysis support under validation and human review—not automated scientific discovery."], layout: "split" },
      { eyebrow: "Reproducibility", headline: ["Methods should be", "open to challenge."], accent: "open to challenge.", body: ["Research becomes more useful when others can understand what was done, why it was done and where uncertainty remains."], layout: "statement" },
      { eyebrow: "Future collaboration", headline: ["Purpose first.", "Partnership second."], accent: "Partnership second.", body: ["Future collaboration would require defined purpose, governance, appropriate approvals and mutual accountability. No current partnership is implied."], layout: "split" },
    ], closing: { headline: ["Learn carefully.", "Share what matters."], accent: "Share what matters.", body: "Knowledge should move forward without personal information being left behind.", ctas: [{ label: "Explore Vascurra Lab", href: "/lab" }] }, next: next(["Questions need a place", "to meet evidence."], "Enter the proposed research-learning environment around Vascurra.", "Vascurra Lab", "/lab"),
  },
  lab: {
    slug: "lab", eyebrow: "Vascurra Lab", title: ["Where lived experience", "meets research."], accent: "meets research.", lead: "A future research-learning environment connecting questions from real life with evidence.", qualifier: "Vascurra Lab is proposed. It does not imply existing studies, datasets, partners, trials or discoveries.", heroArtwork: art("lab-hero", "Two streams converge", "Lived questions and evidence meet without losing their identity.", "16 / 7", "4 / 3", "Two clean cyan-teal-green streams converging into an open research field. No brain or generic laboratory imagery."),
    chapters: [
      { eyebrow: "Lived questions", headline: ["Begin with questions", "that matter to people."], accent: "that matter to people.", body: ["Daily experience can reveal uncertainty and friction worth exploring, while remaining distinct from formal evidence."], layout: "split" },
      { eyebrow: "Evidence", headline: ["Bring the existing record", "into view."], accent: "into view.", body: ["Relevant literature, methods and limitations should provide the foundation for any responsible exploration."], layout: "split", reverse: true },
      { eyebrow: "AI-assisted exploration", headline: ["Explore carefully.", "Validate deliberately."], accent: "Validate deliberately.", body: ["AI may support bounded research tasks, synthesis and analysis. Outputs require structured validation, provenance and human review."], tone: "quiet", layout: "statement" },
      { eyebrow: "The learning loop", headline: ["Question. Evidence. Exploration.", "Review. Learning. Better question."], accent: "Review. Learning. Better question.", body: ["The value is an accountable cycle of inquiry—not an automated engine producing discoveries."], items: ["Question", "Evidence", "AI-assisted exploration", "Human review", "Learning", "Better question"], artwork: art("lab-learning-loop", "The research-learning loop", "Questions and evidence move through governed review.", "16 / 7", "4 / 3", "One open flowing loop through six stages, with human review clearly visible and no corporate process-wheel styling."), tone: "deep", layout: "sequence" },
      { eyebrow: "Consent + governance", headline: ["Lived experience may inspire research.", "Personal information does not silently follow."], accent: "Personal information does not silently follow.", body: ["Any future participation or secondary use would require explicit consent, defined purpose, appropriate permissions and applicable legal and ethical review."], layout: "statement" },
      { eyebrow: "Open knowledge direction", headline: ["Share learning.", "Protect people."], accent: "Protect people.", body: ["Vascurra’s direction is to make useful methods and knowledge easier to scrutinise where appropriate—not to expose personal data or promise that sensitive outputs will be public."], layout: "split" },
    ], closing: { headline: ["Research should begin", "with questions that matter."], accent: "with questions that matter.", body: "Then proceed with evidence, governance and humility.", ctas: [{ label: "Responsible by Design", href: "/responsible" }] }, next: next(["Learning needs", "responsible foundations."], "See how trust, control and evidence are intended to shape the system from the beginning.", "Responsible by Design", "/responsible"),
  },
  responsible: {
    slug: "responsible", eyebrow: "Responsible by Design", title: ["Trust is part", "of the architecture."], accent: "of the architecture.", lead: "Safety, privacy and human control should shape the system from the beginning—not be added later.", heroArtwork: art("responsible-hero", "Controlled information flow", "The person controls purpose-specific paths.", "16 / 7", "4 / 3", "Elegant permission and controlled-flow artwork centred on a person. No giant padlock, shield or compliance badge."),
    chapters: [
      { eyebrow: "Consent + control", headline: ["Participation and sharing", "remain choices."], accent: "remain choices.", body: ["People should understand what they are agreeing to, for what purpose, and how a choice can be revisited."], layout: "split" },
      { eyebrow: "Purpose limitation", headline: ["Use information", "for an understood purpose."], accent: "for an understood purpose.", body: ["Access should follow a legitimate, stated purpose rather than expand simply because information is available."], layout: "split", reverse: true },
      { eyebrow: "Data minimisation", headline: ["Collect what matters.", "Not everything possible."], accent: "Not everything possible.", body: ["Technical possibility is not a reason to collect. A quieter system can protect dignity while reducing unnecessary exposure and noise."], tone: "quiet", layout: "statement" },
      { eyebrow: "Provenance + uncertainty", headline: ["Keep the source visible.", "Keep uncertainty honest."], accent: "Keep uncertainty honest.", body: ["Important information should retain its origin and context. Unknowns should remain visible rather than disappear behind confident language."], items: ["Source", "Context", "Interpretation", "Uncertainty"], layout: "principles" },
      { eyebrow: "Human review", headline: ["Important judgement", "stays human."], accent: "stays human.", body: ["High-impact future outputs require appropriate review paths. A language model must never become the clinical record, permissions system or diagnostic authority."], layout: "statement" },
      { eyebrow: "Responsible claims", headline: ["Evidence", "before claims."], accent: "before claims.", body: ["Ambition can guide research. Public claims must remain bounded by what reliable evidence and appropriate review actually support."], tone: "deep", layout: "statement" },
      { eyebrow: "Safety boundaries", headline: ["Clear limits are", "part of useful design."], accent: "part of useful design.", body: ["The current website provides information about a proposed platform. It does not deliver medical functionality."], items: ["No autonomous diagnosis", "No autonomous treatment decisions", "No medication changes", "No automatic family access", "No silent research use", "No unsupported outcome claims"], layout: "sequence" },
    ], closing: { headline: ["Trust should not sit", "in the footer."], accent: "in the footer.", body: "It belongs in the choices, boundaries and architecture of the whole system.", ctas: [{ label: "Support Vascurra", href: "/support" }] }, next: next(["Responsible ambition needs", "the capacity to proceed carefully."], "Explore ways to support defined development and research without overstating what exists today.", "Support Vascurra", "/support"),
  },
  support: {
    slug: "support", eyebrow: "Support Vascurra", title: ["Help fund", "the next question."], accent: "the next question.", lead: "Support can help Vascurra explore research, responsible AI development, co-design and the infrastructure required to build carefully.", qualifier: "No payments are accepted on this website. Support is not represented as a tax-deductible donation or investment.", heroArtwork: art("support-hero", "Capacity for careful work", "Support branches into defined areas of work.", "16 / 7", "4 / 3", "One stream of support branching into co-design, research, AI capacity, infrastructure and knowledge. No currency or money icon."),
    chapters: [
      { eyebrow: "Support the project", headline: ["Help create", "room to build carefully."], accent: "room to build carefully.", body: ["Mission-aligned support may help Vascurra continue co-design, product exploration and the practical work required to test ideas responsibly."], layout: "split" },
      { eyebrow: "Fund AI research", headline: ["Resource defined work.", "Keep the purpose visible."], accent: "Keep the purpose visible.", body: ["Potential support could fund bounded research activity, compute, literature work or analysis under documented methods and human review."], layout: "split", reverse: true },
      { eyebrow: "Philanthropy", headline: ["Support an ambitious", "human-centred direction."], accent: "human-centred direction.", body: ["Vascurra welcomes conversations with people and organisations whose goals align with careful development. No legal donation status is implied."], tone: "quiet", layout: "statement" },
      { eyebrow: "Clinical + research collaboration", headline: ["Bring expertise", "to the questions."], accent: "to the questions.", body: ["Future design partnerships and research collaboration would begin with shared purpose, governance and clear boundaries—not borrowed logos or implied endorsement."], layout: "split" },
      { eyebrow: "Grants + programmes", headline: ["Build capacity", "without losing discipline."], accent: "without losing discipline.", body: ["Institutional and non-dilutive programmes may help support carefully scoped work where eligibility and terms are appropriate."], layout: "split", reverse: true },
      { eyebrow: "A signature principle", headline: ["Every research contribution", "should leave a trail of knowledge."], accent: "should leave a trail of knowledge.", body: ["Vascurra intends to make the purpose of supported work and what it enabled more understandable where appropriate, without exposing personal or sensitive material."], tone: "deep", layout: "statement" },
    ], closing: { headline: ["Fund the work.", "Share the learning."], accent: "Share the learning.", body: "Support careful progress and keep accountability close to the question.", ctas: [{ label: "Register interest", href: "/access" }, { label: "Contact Vascurra", href: "/contact" }] }, next: next(["Behind the project is", "a human reason to build."], "Read the story, mission and principles that hold the wider Vascurra system together.", "About Vascurra", "/about"),
  },
  about: {
    slug: "about", eyebrow: "About Vascurra", title: ["A human problem.", "An ambitious project."], accent: "An ambitious project.", lead: "Vascurra is being developed around the idea that intelligence can help people navigate complexity without diminishing independence, identity or human judgement.", heroArtwork: art("about-hero", "From one person outward", "A human origin opens into the wider Vascurra system.", "4 / 5", "4 / 5", "One person at the origin with the wider Vascurra system emerging outward through an open ribbon; warm, dignified and not clinical."),
    chapters: [
      { eyebrow: "It began with Dad", headline: ["One family experience.", "A much wider question."], accent: "A much wider question.", body: ["Vascurra began with a father, a retired GP living with early vascular dementia, and a desire to build support with him rather than around him.", "The story is personal. The questions it raises—about context, independence and humane technology—reach much further."], layout: "split" },
      { eyebrow: "The mission", headline: ["Help today. Learn every day.", "Fight for tomorrow."], accent: "Fight for tomorrow.", body: ["Support independence and identity now. Learn carefully from lived experience and evidence. Contribute better questions to longer-term research."], tone: "deep", layout: "statement" },
      { eyebrow: "What we are building", headline: ["One project.", "Different human perspectives."], accent: "Different human perspectives.", body: ["The direction begins with the person and recognises that families, clinicians and researchers have different purposes and permissions."], items: ["Personal", "Family", "Clinician", "Research"], layout: "principles" },
      { eyebrow: "The system", headline: ["Conversation. Interpretation.", "Research-learning."], accent: "Research-learning.", body: ["Veya is the human-facing conversational layer. Vascurra Intelligence is the proposed governed reasoning layer. Vascurra Lab is the future research-learning environment."], items: ["Veya", "Vascurra Intelligence", "Vascurra Lab"], tone: "quiet", layout: "sequence" },
      { eyebrow: "How we build", headline: ["Useful first.", "Responsible throughout."], accent: "Responsible throughout.", body: ["The project should remain human-centred, evidence-informed, privacy-conscious, iterative and open to challenge."], items: ["Human-centred", "Evidence-informed", "Privacy-conscious", "Iterative", "Responsible"], layout: "principles" },
      { eyebrow: "Ambition + discipline", headline: ["Aim high.", "Claim carefully."], accent: "Claim carefully.", body: ["Vascurra can pursue difficult questions without presenting hopes as outcomes or concepts as finished clinical systems."], layout: "statement" },
      { eyebrow: "The future", headline: ["Contribute to better understanding.", "Earn every next step."], accent: "Earn every next step.", body: ["The long-term ambition is to contribute meaningfully to understanding, support, care and research. Progress must be guided by evidence, appropriate governance and the people affected."], layout: "split" },
    ], closing: { headline: ["Build carefully.", "Aim high."], accent: "Aim high.", body: "Support independence. Preserve identity.", ctas: [{ label: "Request access", href: "/access" }] }, next: next(["Help shape", "what Vascurra becomes."], "Register an interest in future co-design, collaboration, support or project updates.", "Request access", "/access"),
  },
} as const satisfies Record<string, InnerStoryPage>;

export type InnerStorySlug = keyof typeof innerSitePages;

export const innerArtworkManifest = (Object.values(innerSitePages) as readonly InnerStoryPage[]).flatMap((page) => [
  { route: `/${page.slug}`, section: "hero", ...page.heroArtwork, humanAppears: ["patient-zero", "family", "about"].some((term) => page.heroArtwork.assetKey.includes(term)), background: "white / transparent", status: "placeholder" as const },
  ...page.chapters.filter((chapter) => chapter.artwork).map((chapter) => ({ route: `/${page.slug}`, section: chapter.eyebrow, ...chapter.artwork!, humanAppears: chapter.artwork!.brief.toLowerCase().includes("person"), background: chapter.tone === "deep" ? "deep navy" : "white / transparent", status: "placeholder" as const })),
]);
