import Link from "next/link";
import { requireDevelopmentSession } from "@/lib/development/server";
import styles from "@/components/veyai/console.module.css";
export const dynamic = "force-dynamic";
export const metadata = { title: "Development previews | Vascurra", robots: { index: false, follow: false } };
export default async function DevelopmentHome() {
  await requireDevelopmentSession();
  return <main id="main" className={styles.shell}><p className={styles.eyebrow}>Local development</p><h1>Build the system.<br />Explore with fixtures.</h1><p>Synthetic examples, isolated from live services and personal information.</p><dl className={styles.metadata}><dt>Data</dt><dd>Fixture</dd><dt>AI</dt><dd>Fixture</dd><dt>Payments</dt><dd>Fixture</dd><dt>Authentication</dt><dd>Development simulation</dd><dt>Live personal data</dt><dd>Disabled</dd></dl><div className={styles.grid}><section className={styles.section}><p className={styles.eyebrow}>Research → Evidence → Human decision</p><h2>VeyAI workstation</h2><p>Run synthetic research, inspect provenance, request critique and record a version-bound decision.</p><Link href="/VeyAI/console">Open the workstation</Link></section><section className={styles.section}><p className={styles.eyebrow}>Institutional memory</p><h2>Vascurra Atlas</h2><p>Keep sources, findings, interpretations, hypotheses and decisions distinct.</p><Link href="/VeyAI/console/atlas">Explore Atlas</Link></section><section className={styles.section}><p className={styles.eyebrow}>Symbolic participation</p><h2>Brain Cells</h2><p>Test selection, safe currency conversion, mock outcomes and participation history.</p><Link href="/development/brain-cells">Explore participation</Link></section><section className={styles.section}><p className={styles.eyebrow}>Person-facing support</p><h2>Veya</h2><p>Explore chosen context, daily support, refusal, uncertainty and clinical boundaries.</p><Link href="/development/veya">Explore Veya journeys</Link></section><section className={styles.section}><p className={styles.eyebrow}>Proposal only</p><h2>Operations</h2><p>Review programme objectives, milestones, dependencies, risks and decision points.</p><Link href="/VeyAI/console/operations">Review the fixture proposal</Link></section><section className={styles.section}><p className={styles.eyebrow}>Scenario only</p><h2>Capital</h2><p>Explore capability, cost categories, readiness and horizon alignment.</p><Link href="/VeyAI/console/capital">Review the fixture scenario</Link></section></div></main>;
}
