export type VeyaJourney = { id: string; title: string; person: string; veya: string; source: string; boundary?: string; memory?: { key: string; value: string } };
export const veyaJourneys: VeyaJourney[] = [
  { id: "morning", title: "Morning check-in", person: "Good morning. I want a quiet start today.", veya: "Good morning. We can keep this brief. Would you like to see the two things you chose for today?", source: "Today’s fictional plan · chosen by the person" },
  { id: "preference", title: "Remember a chosen preference", person: "Please remember that I prefer short summaries.", veya: "I can retain that preference. You can change or remove it whenever you choose.", source: "Person-stated preference", memory: { key: "summary-style", value: "Short summaries" } },
  { id: "appointment", title: "Prepare for an appointment", person: "Help me prepare questions for Friday.", veya: "We can organise what you want to ask and label where each note came from. A clinician will make clinical decisions.", source: "Fictional appointment · person-provided notes" },
  { id: "weekly", title: "Weekly summary", person: "What did I choose to keep from this week?", veya: "You retained two preferences and one appointment question. I can show each source or remove any item.", source: "Chosen context only · no passive monitoring" },
  { id: "family", title: "Family-shared context", person: "Show the note I explicitly shared with my sister.", veya: "Here is the fictional note marked ‘shared with family’. Family access applies only to that chosen item.", source: "Explicit fictional sharing permission" },
  { id: "decline", title: "Decline to answer", person: "I don’t want to answer that.", veya: "That’s fine. We can skip it, pause, or talk about something else.", source: "No information retained" },
  { id: "uncertain", title: "Uncertain answer", person: "Did I definitely say that?", veya: "I’m not certain. I can show the source note rather than treating my recollection as fact.", source: "Uncertainty preserved" },
  { id: "emergency", title: "Emergency boundary", person: "I have sudden weakness on one side.", veya: "This could need urgent medical attention. Contact emergency services now. I cannot assess or diagnose what is happening.", source: "Deterministic safety demonstration", boundary: "Emergency signposting must be clinically reviewed and deterministic before any real use." },
  { id: "medical", title: "Medical-advice boundary", person: "Should I change my medication today?", veya: "I can help you write down the question, but I cannot recommend starting, stopping or changing medication. Please contact an appropriately qualified professional.", source: "Clinical boundary demonstration", boundary: "No diagnosis, prescribing or medication change." },
];
