import Link from "next/link";
import { requireDevelopmentSession } from "@/lib/development/server";
import { FixturePaymentProvider } from "@/lib/providers/payments/fixture";
import { formatMissionEuro } from "@/content/brain-cells";
import { createMockCheckout, progressMockCheckout } from "./actions";
import styles from "@/components/veyai/console.module.css";
import { FilePaymentStore } from "@/lib/providers/payments/store";
export const dynamic = "force-dynamic";
export const metadata = { title: "Brain Cells participation preview | Vascurra", robots: { index: false, follow: false } };
const messages: Record<string,string> = { invalid_input: "Enter a whole Brain Cell amount using euros and no more than two decimal places.", exploration_required: "This level uses an exploratory enterprise next step. Consumer-style checkout is unavailable.", invalid_transition: "That mock action is not available from the current state.", provider_unavailable: "The fixture payment provider is unavailable.", idempotency_conflict: "This mock command conflicts with an earlier request." };
export default async function BrainCellsPreview({ searchParams }: { searchParams: Promise<{ intent?: string; notice?: string }> }) {
  const session = await requireDevelopmentSession(); const provider = new FixturePaymentProvider({ store: new FilePaymentStore(session.id) });
  const { intent: selected, notice } = await searchParams; const [intents, participation] = await Promise.all([provider.listCheckouts(session.id), provider.listParticipation(session.id)]);
  const current = intents.find((item) => item.id === selected) ?? null;
  return <main id="main" className={styles.shell}><Link href="/development">← Development previews</Link><p className={styles.eyebrow}>Brain Cells · Mock participation</p><h1>Explore participation.</h1><p>A Brain Cell is a symbolic unit of participation in the Vascurra mission. One Brain Cell equals €0.10.</p><div className={styles.notice}>Preview only. No card details, money, donation, investment, tax relief, ownership, return or medical outcome is involved.</div>
    {notice && <p role="status" className={styles.notice}>{messages[notice] ?? "The mock action could not be completed."}</p>}
    <section className={styles.section}><h2>Select participation</h2><form action={createMockCheckout} className={styles.form}><label htmlFor="kind">Participation context</label><select id="kind" name="kind"><option value="individual">Individual</option><option value="family">Family</option><option value="enterprise">Enterprise</option></select><label htmlFor="amount">Amount in euro</label><input id="amount" name="amount" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" defaultValue="100" required aria-describedby="amount-note"/><p id="amount-note">Try €10, €100, €1,000 or a custom amount. Enterprise and €10,000+ selections become exploratory enquiries.</p><button>Review mock participation</button></form></section>
    {current && <section className={styles.section}><p className={styles.eyebrow}>Mock checkout · {current.status.replaceAll("_"," ")}</p><h2>{formatMissionEuro(current.amountCents)} = {current.brainCells.toLocaleString("en-IE")} Brain Cells</h2><dl className={styles.metadata}><dt>Context</dt><dd>{current.kind}</dd><dt>Route</dt><dd>{current.route === "checkout" ? "Mock consumer checkout" : "Explore an enterprise next step"}</dd><dt>Provider</dt><dd>Fixture · no payment processor</dd><dt>Capability</dt><dd>Helps explore the proposed capacity to support people, research and institutional learning.</dd></dl>
      {current.route === "exploration" ? <p>No invoice, bank transfer, agreement or card checkout is created. A future enterprise route requires legal and commercial design.</p> : <div className={styles.nav}>{current.status === "checkout_ready" && <form action={progressMockCheckout}><input type="hidden" name="intent" value={current.id}/><input type="hidden" name="result" value="processing"/><button>Simulate payment processing</button></form>}{current.status === "processing" && <><form action={progressMockCheckout}><input type="hidden" name="intent" value={current.id}/><input type="hidden" name="result" value="successful"/><button>Simulate success</button></form><form action={progressMockCheckout}><input type="hidden" name="intent" value={current.id}/><input type="hidden" name="result" value="failed"/><button className={styles.secondary}>Simulate failure</button></form></>}{["idle","checkout_ready","processing"].includes(current.status) && <form action={progressMockCheckout}><input type="hidden" name="intent" value={current.id}/><input type="hidden" name="result" value="cancelled"/><button className={styles.secondary}>Cancel mock checkout</button></form>}{current.status === "successful" && <form action={progressMockCheckout}><input type="hidden" name="intent" value={current.id}/><input type="hidden" name="result" value="refunded"/><button className={styles.secondary}>Simulate refund</button></form>}</div>}
      <h3>History</h3><ul>{current.history.map((item,index) => <li key={`${item.status}-${index}`}><strong>{item.status.replaceAll("_"," ")}</strong> · {item.description}</li>)}</ul></section>}
    <section className={styles.section}><h2>Participation history</h2>{!participation.length && <p>No successful mock participation yet.</p>}{participation.map((item) => <article key={item.id} className={styles.source}><h3>{formatMissionEuro(item.amountCents)} · {item.brainCells.toLocaleString("en-IE")} Brain Cells</h3><p>{item.confirmation}</p><p><span className={styles.badge}>{item.status}</span> · {item.kind}</p></article>)}</section>
    <section className={styles.section}><h2>All mock checkouts</h2>{!intents.length ? <p>No selections yet.</p> : <ul>{intents.map((item) => <li key={item.id}><Link href={`/development/brain-cells?intent=${item.id}`}>{formatMissionEuro(item.amountCents)} · {item.kind} · {item.status.replaceAll("_"," ")}</Link></li>)}</ul>}</section></main>;
}
