import { personal } from "@/content/personal";
import { ArtworkToFollow, CTA, CTAGroup, NextChapter, SafetyBoundary, VascurraHeadline } from "./inner-page";
import styles from "./personal-page.module.css";

export function PersonalPage() {
  return <main className={styles.page} id="main">
    <section className={styles.hero} aria-labelledby="personal-title"><div className={styles.shell}><div className={styles.heroGrid}><div className={styles.heroCopy}><p className={styles.eyebrow}>{personal.hero.eyebrow}</p><VascurraHeadline as="h1" id="personal-title" lines={personal.hero.headline} accent={personal.hero.accent} /><p className={styles.proposition}>{personal.hero.proposition}</p><p className={styles.body}>{personal.hero.body}</p><SafetyBoundary>{personal.hero.qualifier}</SafetyBoundary><CTAGroup><CTA href="/access">Request access</CTA><CTA href="/how-it-works" secondary>See how it works</CTA></CTAGroup></div><ArtworkToFollow artwork={personal.hero.artwork} className={styles.heroArt} /></div></div></section>

    <section className={styles.everyday} aria-labelledby="everyday-title"><div className={styles.shell}><p className={styles.eyebrow}>{personal.everyday.eyebrow}</p><div className={styles.introGrid}><VascurraHeadline id="everyday-title" lines={personal.everyday.headline} accent={personal.everyday.accent} /><div><p className={styles.lead}>{personal.everyday.lead}</p><p className={styles.body}>{personal.everyday.body}</p></div></div><ol className={styles.dayline}>{personal.everyday.sequence.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol><SafetyBoundary>{personal.everyday.qualifier}</SafetyBoundary></div></section>

    <section className={styles.adaptive} aria-labelledby="adaptive-title"><div className={styles.shell}><div className={styles.adaptiveIntro}><div><p className={styles.eyebrow}>{personal.adaptive.eyebrow}</p><VascurraHeadline id="adaptive-title" lines={personal.adaptive.headline} accent={personal.adaptive.accent} /></div><div>{personal.adaptive.body.map((paragraph) => <p className={styles.body} key={paragraph}>{paragraph}</p>)}</div></div><ArtworkToFollow artwork={personal.adaptive.artwork} /><ol className={styles.supportStages}>{personal.adaptive.stages.map((stage, index) => <li key={stage}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage}</strong><small>{personal.adaptive.details[index] ?? personal.adaptive.details.at(-1)}</small></li>)}</ol></div></section>

    <section className={styles.veya} aria-labelledby="veya-title"><div className={styles.shell}><div className={styles.featureGrid}><ArtworkToFollow artwork={personal.veya.artwork} /><div><p className={styles.eyebrow}>{personal.veya.eyebrow}</p><VascurraHeadline id="veya-title" lines={personal.veya.headline} accent={personal.veya.accent} /><p className={styles.lead}>{personal.veya.lead}</p><p className={styles.body}>{personal.veya.body}</p><p className={styles.distinction}>{personal.veya.distinction}</p><SafetyBoundary>{personal.veya.safety}</SafetyBoundary><CTAGroup><CTA href="/veya" secondary>Explore Veya</CTA></CTAGroup></div></div></div></section>

    <section className={styles.preparation} aria-labelledby="preparation-title"><div className={styles.shell}><p className={styles.eyebrow}>{personal.preparation.eyebrow}</p><VascurraHeadline id="preparation-title" lines={personal.preparation.headline} accent={personal.preparation.accent} /><p className={styles.preparationLead}>{personal.preparation.proposition}</p><ul className={styles.questions}>{personal.preparation.questions.map((question, index) => <li key={question}><span>{String(index + 1).padStart(2, "0")}</span>{question}</li>)}</ul></div></section>

    <section className={styles.control} aria-labelledby="control-title"><div className={styles.shell}><div className={styles.introGrid}><div><p className={styles.eyebrow}>{personal.control.eyebrow}</p><VascurraHeadline id="control-title" lines={personal.control.headline} accent={personal.control.accent} /></div><div><p className={styles.lead}>{personal.control.lead}</p><p className={styles.body}>{personal.control.body}</p></div></div><ArtworkToFollow artwork={personal.control.artwork} /><ul className={styles.destinations}>{personal.control.destinations.map((item, index) => <li className={index === 0 ? styles.destinationPrimary : undefined} key={item}>{item}</li>)}</ul></div></section>

    <section className={styles.dignity} aria-labelledby="dignity-title"><div className={styles.shell}><p className={styles.eyebrow}>{personal.dignity.eyebrow}</p><VascurraHeadline id="dignity-title" lines={personal.dignity.headline} accent={personal.dignity.accent} /><div className={styles.dignityGrid}><div>{personal.dignity.body.map((paragraph) => <p className={styles.body} key={paragraph}>{paragraph}</p>)}</div><ul className={styles.principles}>{personal.dignity.principles.map((principle) => <li key={principle}>{principle}</li>)}</ul></div></div></section>

    <section className={styles.closing} aria-labelledby="closing-title"><div className={styles.shell}><p className={styles.eyebrow}>{personal.closing.eyebrow}</p><VascurraHeadline id="closing-title" lines={personal.closing.headline} accent={personal.closing.accent} align="center" /><p className={styles.closingBody}>{personal.closing.body}</p><CTAGroup align="center"><CTA href="/access">Request access</CTA><CTA href="/about" secondary>About Vascurra</CTA></CTAGroup></div></section>
    <NextChapter {...personal.next} />
  </main>;
}
